In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe:

In [2]:
labels = pd.read_csv('labels.csv')

In [7]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

### Start with assessing the radiologist's performance:
* Assess the _accuracy_ of the radiologist by just looking at the percent of cases that they correctly labeled
* Next, look at the true positive and true negative rates of the radiologist by generating a _confusion matrix_ 

In [8]:
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)

In [9]:
radiologist_accuracy

0.8993288590604027

In [10]:
confusion_matrix(labels.perfect_labeler.values,labels.radiologist.values,labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

### Now look at the algorithm's performance compared to the perfect labeler:
* Since the algorithm doesn't create a binary label, it instead returns a _probability_ of cancer, choose a probability cut-off to use for the algorithm's labeling of cancer vs. bening. _(Hint: 0.5 is a reasonable starting place)_
* Start with assessing _accuracy_ again here
* Generate a confusion matrix

In [13]:
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix

In [16]:
# Load data
labels = pd.read_csv('labels.csv')

In [22]:
#Step 1: Binarize algorithm predictions using a threshold 
threshold = 0.5 
labels['algorithm_pred'] = labels['algorithm'].apply(lambda x: "cancer" if x >= threshold else "benign")
                                                     

In [24]:
#Step 2: Compute accuracy
algorithm_accuracy = accuracy_score(labels['perfect_labeler'], labels['algorithm_pred'])
print("Algorithm Accuracy:", algorithm_accuracy)

Algorithm Accuracy: 0.8859060402684564


In [25]:
#Step 3: Generate confusion matrix
cm = confusion_matrix(labels['perfect_labeler'], labels['algorithm_pred'], labels=["cancer", "benign"])
print("Confusion Matrix: \n", cm)

Confusion Matrix: 
 [[ 21   8]
 [  9 111]]


What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [27]:
#Step 1: Binarize algorithm predictions using a threshold 
threshold = 0.6 
labels['algorithm_pred'] = labels['algorithm'].apply(lambda x: "cancer" if x >= threshold else "benign")

#Step 2: Compute accuracy
algorithm_accuracy = accuracy_score(labels['perfect_labeler'], labels['algorithm_pred'])
print("Algorithm Accuracy:", algorithm_accuracy)

#Step 3: Generate confusion matrix
cm = confusion_matrix(labels['perfect_labeler'], labels['algorithm_pred'], labels=["cancer", "benign"])
print("Confusion Matrix: \n", cm)
                 

Algorithm Accuracy: 0.9060402684563759
Confusion Matrix: 
 [[ 20   9]
 [  5 115]]


In [28]:
#Step 1: Binarize algorithm predictions using a threshold 
threshold = 0.4
labels['algorithm_pred'] = labels['algorithm'].apply(lambda x: "cancer" if x >= threshold else "benign")

#Step 2: Compute accuracy
algorithm_accuracy = accuracy_score(labels['perfect_labeler'], labels['algorithm_pred'])
print("Algorithm Accuracy:", algorithm_accuracy)

#Step 3: Generate confusion matrix
cm = confusion_matrix(labels['perfect_labeler'], labels['algorithm_pred'], labels=["cancer", "benign"])
print("Confusion Matrix: \n", cm)

Algorithm Accuracy: 0.8590604026845637
Confusion Matrix: 
 [[ 25   4]
 [ 17 103]]


### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist. 

In [29]:
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix

# Load data
labels = pd.read_csv('labels.csv')

# Set threshold and compute binary predictions
threshold = 0.5
labels['algorithm_pred'] = labels['algorithm'].apply(lambda x: "cancer" if x >= threshold else "benign")

# Compare to radiologist instead of perfect_labeler
accuracy = accuracy_score(labels['radiologist'], labels['algorithm_pred'])
print("Algorithm vs Radiologist Accuracy:", accuracy)

# Confusion matrix with radiologist as the reference
cm = confusion_matrix(labels['radiologist'], labels['algorithm_pred'], labels=["cancer", "benign"])
print("Confusion Matrix (vs Radiologist):\n", cm)

# Extract TP, FN, FP, TN
TP = cm[0, 0]  # radiologist = cancer, algorithm = cancer
FN = cm[0, 1]  # radiologist = cancer, algorithm = benign
FP = cm[1, 0]  # radiologist = benign, algorithm = cancer
TN = cm[1, 1]  # radiologist = benign, algorithm = benign

print(f"TP: {TP}, FN: {FN}, FP: {FP}, TN: {TN}")

Algorithm vs Radiologist Accuracy: 0.8657718120805369
Confusion Matrix (vs Radiologist):
 [[ 23  13]
 [  7 106]]
TP: 23, FN: 13, FP: 7, TN: 106


## Reflection: 
* In the above exercise you assess performances of a human as well as of an algorithm against a 'perfect labeler' and also against each other. 
* Does accuracy seem like the appropriate statistic to use when evaluating these labels? Why or why not? 
* In what clinical settings does it seem more or less acceptable to have a high level of FNs? FPs? 
* How did changing the threshold on the algorithm performance change the different performance statistics? 
* How did your opinion of the algorithm's performance change when you started comparing it to a radiologist instead of the perfect labeler? What does this mean for a real-world scenario when a perfect labeler doesn't exist, and we only have a radiologist's read to base our performance on? 

In [ ]:
Accuracy is insufficient alone and metrics need to be aligned with clinical risks of the testing. 
FP vs. FP tolerance depends on clinical context and downstream consequences. 
Threshold tuing offers control over trade-offs in sensitivity / specificity. 
When the "truth" is expert opinion, benchmarking against radiologists or other experts is both realistic and meaningful.
